export const HOVER_PRODUCT_SELECTOR = 'HOVER_PRODUCT_SELECTOR';
export const LEAVE_PRODUCT_SELECTOR = 'LEAVE_PRODUCT_SELECTOR';
export const TOGGLE_PRODUCT_SELECTOR = 'TOGGLE_PRODUCT_SELECTOR';

export const HOVER_PRODUCT_MODAL = 'HOVER_PRODUCT_MODAL';
export const LEAVE_PRODUCT_MODAL = 'LEAVE_PRODUCT_MODAL';

export const SELECT_PRODUCT = 'SELECT_PRODUCT';
export const SELECT_BUY = 'SELECT_BUY';
export const SELECT_SELL = 'SELECT_SELL';
export const CHECK_WHETHER_INPUT_IS_FIAT = 'CHECK_WHETHER_INPUT_IS_FIAT';

export const UPDATE_AMOUNT = 'UPDATE_AMOUNT';
export const CALCULATE_QUOTE = 'CALCULATE_QUOTE';
export const RECEIVE_QUOTE = 'RECEIVE_QUOTE';
